name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

       # - name: Log in to Docker Hub
       # uses: docker/login-action@v2
        with:
         #  username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Docker container
        run: |
          docker stop opsoura-site || true
          docker rm opsoura-site || true
          docker run -d --name opsoura-site -p 8081:80 ${{ secrets.DOCKER_IMAGE }}

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test server
        run: |
          sleep 10
          '[[ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:881) == "200" ]]'
