name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t opsoura-site:latest .
          docker tag opsoura-site:latest ${{ secrets.DOCKER_USERNAME }}/opsoura-site:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/opsoura-site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Run Docker container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/opsoura-site:latest
          docker stop opsoura-site || true
          docker rm opsoura-site || true
          docker run -d --name opsoura-site -p 8081:80 ${{ secrets.DOCKER_USERNAME }}/opsoura-site:latest

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test server
        run: |
          sleep 10
          '[[ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081) == "200" ]]'
